#ifndef SIN_COS_SELECTOR_H
#define SIN_COS_SELECTOR_H


#ifdef USE_CHAR_THETA
#define SIN_THETA(x) photonOptions.sinTheta[x]
#define COS_THETA(x) photonOptions.cosTheta[x]
#define SIN_PHI(x) photonOptions.sinTheta[x]
#define COS_PHI(x) photonOptions.cosTheta[x]


#else // #ifdef USE_CHAR_THETA
#include "expanded_all_functions.h"


#if defined(SIN_THETA_IS_SIN_CRLIBM)
#define SIN_THETA(x) sin_crlibm(x)
#elif defined(SIN_THETA_IS_SIN_GLIBC)
#define SIN_THETA(x) sin_glibc(x)
#elif defined(SIN_THETA_IS_SINF_GLIBC)
#define SIN_THETA(x) sinf_glibc(x)
#elif defined(SIN_THETA_IS_ML2_SIN_1)
#define SIN_THETA(x) ml2_sin_1(x)
#elif defined(SIN_THETA_IS_ML2_SIN_3)
#define SIN_THETA(x) ml2_sin_3(x)
#elif defined(SIN_THETA_IS_ML2_SIN_5)
#define SIN_THETA(x) ml2_sin_5(x)
#elif defined(SIN_THETA_IS_ML2_SIN_7)
#define SIN_THETA(x) ml2_sin_7(x)
#elif defined(SIN_THETA_IS_ML2_SIN_9)
#define SIN_THETA(x) ml2_sin_9(x)
#elif defined(SIN_THETA_IS_ML2_SIN_11)
#define SIN_THETA(x) ml2_sin_11(x)
#elif defined(SIN_THETA_IS_ML2_SIN_13)
#define SIN_THETA(x) ml2_sin_13(x)
#elif defined(SIN_THETA_IS_ML2_SIN_15)
#define SIN_THETA(x) ml2_sin_15(x)
#elif defined(SIN_THETA_IS_ML2_SIN_17)
#define SIN_THETA(x) ml2_sin_17(x)
#elif defined(SIN_THETA_IS_ML2_SIN_19)
#define SIN_THETA(x) ml2_sin_19(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_3)
#define SIN_THETA(x) ml2_wide_sin_3(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_5)
#define SIN_THETA(x) ml2_wide_sin_5(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_7)
#define SIN_THETA(x) ml2_wide_sin_7(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_9)
#define SIN_THETA(x) ml2_wide_sin_9(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_11)
#define SIN_THETA(x) ml2_wide_sin_11(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_13)
#define SIN_THETA(x) ml2_wide_sin_13(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_15)
#define SIN_THETA(x) ml2_wide_sin_15(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_17)
#define SIN_THETA(x) ml2_wide_sin_17(x)
#elif defined(SIN_THETA_IS_ML2_WIDE_SIN_19)
#define SIN_THETA(x) ml2_wide_sin_19(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_1)
#define SIN_THETA(x) ml2_raw_sin_1(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_3)
#define SIN_THETA(x) ml2_raw_sin_3(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_5)
#define SIN_THETA(x) ml2_raw_sin_5(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_7)
#define SIN_THETA(x) ml2_raw_sin_7(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_9)
#define SIN_THETA(x) ml2_raw_sin_9(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_11)
#define SIN_THETA(x) ml2_raw_sin_11(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_13)
#define SIN_THETA(x) ml2_raw_sin_13(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_15)
#define SIN_THETA(x) ml2_raw_sin_15(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_17)
#define SIN_THETA(x) ml2_raw_sin_17(x)
#elif defined(SIN_THETA_IS_ML2_RAW_SIN_19)
#define SIN_THETA(x) ml2_raw_sin_19(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_3)
#define SIN_THETA(x) ml2_raw_wide_sin_3(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_5)
#define SIN_THETA(x) ml2_raw_wide_sin_5(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_7)
#define SIN_THETA(x) ml2_raw_wide_sin_7(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_9)
#define SIN_THETA(x) ml2_raw_wide_sin_9(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_11)
#define SIN_THETA(x) ml2_raw_wide_sin_11(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_13)
#define SIN_THETA(x) ml2_raw_wide_sin_13(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_15)
#define SIN_THETA(x) ml2_raw_wide_sin_15(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_17)
#define SIN_THETA(x) ml2_raw_wide_sin_17(x)
#elif defined(SIN_THETA_IS_ML2_RAW_WIDE_SIN_19)
#define SIN_THETA(x) ml2_raw_wide_sin_19(x)
#elif defined(SIN_THETA_IS_SIN_OPENLIBM)
#define SIN_THETA(x) sin_openlibm(x)
#elif defined(SIN_THETA_IS_SINF_OPENLIBM)
#define SIN_THETA(x) sinf_openlibm(x)
#elif defined(SIN_THETA_IS_SIN_POVRAY)
#define SIN_THETA(x) sin_povray(x)
#elif defined(SIN_THETA_IS_SIN_VDT)
#define SIN_THETA(x) sin_vdt(x)
#elif defined(SIN_THETA_IS_SINF_VDT)
#define SIN_THETA(x) sinf_vdt(x)
#else
#define SIN_THETA(x) sin_crlibm(x)
#endif




#if defined(COS_THETA_IS_COS_CRLIBM)
#define COS_THETA(x) cos_crlibm(x)
#elif defined(COS_THETA_IS_COS_GLIBC)
#define COS_THETA(x) cos_glibc(x)
#elif defined(COS_THETA_IS_COSF_GLIBC)
#define COS_THETA(x) cosf_glibc(x)
#elif defined(COS_THETA_IS_ML2_COS_2)
#define COS_THETA(x) ml2_cos_2(x)
#elif defined(COS_THETA_IS_ML2_COS_4)
#define COS_THETA(x) ml2_cos_4(x)
#elif defined(COS_THETA_IS_ML2_COS_6)
#define COS_THETA(x) ml2_cos_6(x)
#elif defined(COS_THETA_IS_ML2_COS_8)
#define COS_THETA(x) ml2_cos_8(x)
#elif defined(COS_THETA_IS_ML2_COS_10)
#define COS_THETA(x) ml2_cos_10(x)
#elif defined(COS_THETA_IS_ML2_COS_12)
#define COS_THETA(x) ml2_cos_12(x)
#elif defined(COS_THETA_IS_ML2_COS_14)
#define COS_THETA(x) ml2_cos_14(x)
#elif defined(COS_THETA_IS_ML2_COS_16)
#define COS_THETA(x) ml2_cos_16(x)
#elif defined(COS_THETA_IS_ML2_COS_18)
#define COS_THETA(x) ml2_cos_18(x)
#elif defined(COS_THETA_IS_ML2_COS_20)
#define COS_THETA(x) ml2_cos_20(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_2)
#define COS_THETA(x) ml2_wide_cos_2(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_6)
#define COS_THETA(x) ml2_wide_cos_6(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_8)
#define COS_THETA(x) ml2_wide_cos_8(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_12)
#define COS_THETA(x) ml2_wide_cos_12(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_14)
#define COS_THETA(x) ml2_wide_cos_14(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_18)
#define COS_THETA(x) ml2_wide_cos_18(x)
#elif defined(COS_THETA_IS_ML2_WIDE_COS_20)
#define COS_THETA(x) ml2_wide_cos_20(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_2)
#define COS_THETA(x) ml2_raw_cos_2(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_4)
#define COS_THETA(x) ml2_raw_cos_4(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_6)
#define COS_THETA(x) ml2_raw_cos_6(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_8)
#define COS_THETA(x) ml2_raw_cos_8(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_10)
#define COS_THETA(x) ml2_raw_cos_10(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_12)
#define COS_THETA(x) ml2_raw_cos_12(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_14)
#define COS_THETA(x) ml2_raw_cos_14(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_16)
#define COS_THETA(x) ml2_raw_cos_16(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_18)
#define COS_THETA(x) ml2_raw_cos_18(x)
#elif defined(COS_THETA_IS_ML2_RAW_COS_20)
#define COS_THETA(x) ml2_raw_cos_20(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_2)
#define COS_THETA(x) ml2_raw_wide_cos_2(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_6)
#define COS_THETA(x) ml2_raw_wide_cos_6(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_8)
#define COS_THETA(x) ml2_raw_wide_cos_8(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_12)
#define COS_THETA(x) ml2_raw_wide_cos_12(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_14)
#define COS_THETA(x) ml2_raw_wide_cos_14(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_18)
#define COS_THETA(x) ml2_raw_wide_cos_18(x)
#elif defined(COS_THETA_IS_ML2_RAW_WIDE_COS_20)
#define COS_THETA(x) ml2_raw_wide_cos_20(x)
#elif defined(COS_THETA_IS_COS_OPENLIBM)
#define COS_THETA(x) cos_openlibm(x)
#elif defined(COS_THETA_IS_COSF_OPENLIBM)
#define COS_THETA(x) cosf_openlibm(x)
#elif defined(COS_THETA_IS_COS_POVRAY)
#define COS_THETA(x) cos_povray(x)
#elif defined(COS_THETA_IS_COS_VDT)
#define COS_THETA(x) cos_vdt(x)
#elif defined(COS_THETA_IS_COSF_VDT)
#define COS_THETA(x) cosf_vdt(x)
#else
#define COS_THETA(x) cos_crlibm(x)
#endif




#if defined(SIN_PHI_IS_SIN_CRLIBM)
#define SIN_PHI(x) sin_crlibm(x)
#elif defined(SIN_PHI_IS_SIN_GLIBC)
#define SIN_PHI(x) sin_glibc(x)
#elif defined(SIN_PHI_IS_SINF_GLIBC)
#define SIN_PHI(x) sinf_glibc(x)
#elif defined(SIN_PHI_IS_ML2_SIN_1)
#define SIN_PHI(x) ml2_sin_1(x)
#elif defined(SIN_PHI_IS_ML2_SIN_3)
#define SIN_PHI(x) ml2_sin_3(x)
#elif defined(SIN_PHI_IS_ML2_SIN_5)
#define SIN_PHI(x) ml2_sin_5(x)
#elif defined(SIN_PHI_IS_ML2_SIN_7)
#define SIN_PHI(x) ml2_sin_7(x)
#elif defined(SIN_PHI_IS_ML2_SIN_9)
#define SIN_PHI(x) ml2_sin_9(x)
#elif defined(SIN_PHI_IS_ML2_SIN_11)
#define SIN_PHI(x) ml2_sin_11(x)
#elif defined(SIN_PHI_IS_ML2_SIN_13)
#define SIN_PHI(x) ml2_sin_13(x)
#elif defined(SIN_PHI_IS_ML2_SIN_15)
#define SIN_PHI(x) ml2_sin_15(x)
#elif defined(SIN_PHI_IS_ML2_SIN_17)
#define SIN_PHI(x) ml2_sin_17(x)
#elif defined(SIN_PHI_IS_ML2_SIN_19)
#define SIN_PHI(x) ml2_sin_19(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_3)
#define SIN_PHI(x) ml2_wide_sin_3(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_5)
#define SIN_PHI(x) ml2_wide_sin_5(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_7)
#define SIN_PHI(x) ml2_wide_sin_7(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_9)
#define SIN_PHI(x) ml2_wide_sin_9(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_11)
#define SIN_PHI(x) ml2_wide_sin_11(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_13)
#define SIN_PHI(x) ml2_wide_sin_13(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_15)
#define SIN_PHI(x) ml2_wide_sin_15(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_17)
#define SIN_PHI(x) ml2_wide_sin_17(x)
#elif defined(SIN_PHI_IS_ML2_WIDE_SIN_19)
#define SIN_PHI(x) ml2_wide_sin_19(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_1)
#define SIN_PHI(x) ml2_raw_sin_1(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_3)
#define SIN_PHI(x) ml2_raw_sin_3(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_5)
#define SIN_PHI(x) ml2_raw_sin_5(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_7)
#define SIN_PHI(x) ml2_raw_sin_7(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_9)
#define SIN_PHI(x) ml2_raw_sin_9(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_11)
#define SIN_PHI(x) ml2_raw_sin_11(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_13)
#define SIN_PHI(x) ml2_raw_sin_13(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_15)
#define SIN_PHI(x) ml2_raw_sin_15(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_17)
#define SIN_PHI(x) ml2_raw_sin_17(x)
#elif defined(SIN_PHI_IS_ML2_RAW_SIN_19)
#define SIN_PHI(x) ml2_raw_sin_19(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_3)
#define SIN_PHI(x) ml2_raw_wide_sin_3(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_5)
#define SIN_PHI(x) ml2_raw_wide_sin_5(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_7)
#define SIN_PHI(x) ml2_raw_wide_sin_7(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_9)
#define SIN_PHI(x) ml2_raw_wide_sin_9(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_11)
#define SIN_PHI(x) ml2_raw_wide_sin_11(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_13)
#define SIN_PHI(x) ml2_raw_wide_sin_13(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_15)
#define SIN_PHI(x) ml2_raw_wide_sin_15(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_17)
#define SIN_PHI(x) ml2_raw_wide_sin_17(x)
#elif defined(SIN_PHI_IS_ML2_RAW_WIDE_SIN_19)
#define SIN_PHI(x) ml2_raw_wide_sin_19(x)
#elif defined(SIN_PHI_IS_SIN_OPENLIBM)
#define SIN_PHI(x) sin_openlibm(x)
#elif defined(SIN_PHI_IS_SINF_OPENLIBM)
#define SIN_PHI(x) sinf_openlibm(x)
#elif defined(SIN_PHI_IS_SIN_POVRAY)
#define SIN_PHI(x) sin_povray(x)
#elif defined(SIN_PHI_IS_SIN_VDT)
#define SIN_PHI(x) sin_vdt(x)
#elif defined(SIN_PHI_IS_SINF_VDT)
#define SIN_PHI(x) sinf_vdt(x)
#else
#define SIN_PHI(x) sin_crlibm(x)
#endif




#if defined(COS_PHI_IS_COS_CRLIBM)
#define COS_PHI(x) cos_crlibm(x)
#elif defined(COS_PHI_IS_COS_GLIBC)
#define COS_PHI(x) cos_glibc(x)
#elif defined(COS_PHI_IS_COSF_GLIBC)
#define COS_PHI(x) cosf_glibc(x)
#elif defined(COS_PHI_IS_ML2_COS_2)
#define COS_PHI(x) ml2_cos_2(x)
#elif defined(COS_PHI_IS_ML2_COS_4)
#define COS_PHI(x) ml2_cos_4(x)
#elif defined(COS_PHI_IS_ML2_COS_6)
#define COS_PHI(x) ml2_cos_6(x)
#elif defined(COS_PHI_IS_ML2_COS_8)
#define COS_PHI(x) ml2_cos_8(x)
#elif defined(COS_PHI_IS_ML2_COS_10)
#define COS_PHI(x) ml2_cos_10(x)
#elif defined(COS_PHI_IS_ML2_COS_12)
#define COS_PHI(x) ml2_cos_12(x)
#elif defined(COS_PHI_IS_ML2_COS_14)
#define COS_PHI(x) ml2_cos_14(x)
#elif defined(COS_PHI_IS_ML2_COS_16)
#define COS_PHI(x) ml2_cos_16(x)
#elif defined(COS_PHI_IS_ML2_COS_18)
#define COS_PHI(x) ml2_cos_18(x)
#elif defined(COS_PHI_IS_ML2_COS_20)
#define COS_PHI(x) ml2_cos_20(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_2)
#define COS_PHI(x) ml2_wide_cos_2(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_6)
#define COS_PHI(x) ml2_wide_cos_6(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_8)
#define COS_PHI(x) ml2_wide_cos_8(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_12)
#define COS_PHI(x) ml2_wide_cos_12(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_14)
#define COS_PHI(x) ml2_wide_cos_14(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_18)
#define COS_PHI(x) ml2_wide_cos_18(x)
#elif defined(COS_PHI_IS_ML2_WIDE_COS_20)
#define COS_PHI(x) ml2_wide_cos_20(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_2)
#define COS_PHI(x) ml2_raw_cos_2(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_4)
#define COS_PHI(x) ml2_raw_cos_4(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_6)
#define COS_PHI(x) ml2_raw_cos_6(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_8)
#define COS_PHI(x) ml2_raw_cos_8(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_10)
#define COS_PHI(x) ml2_raw_cos_10(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_12)
#define COS_PHI(x) ml2_raw_cos_12(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_14)
#define COS_PHI(x) ml2_raw_cos_14(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_16)
#define COS_PHI(x) ml2_raw_cos_16(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_18)
#define COS_PHI(x) ml2_raw_cos_18(x)
#elif defined(COS_PHI_IS_ML2_RAW_COS_20)
#define COS_PHI(x) ml2_raw_cos_20(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_2)
#define COS_PHI(x) ml2_raw_wide_cos_2(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_6)
#define COS_PHI(x) ml2_raw_wide_cos_6(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_8)
#define COS_PHI(x) ml2_raw_wide_cos_8(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_12)
#define COS_PHI(x) ml2_raw_wide_cos_12(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_14)
#define COS_PHI(x) ml2_raw_wide_cos_14(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_18)
#define COS_PHI(x) ml2_raw_wide_cos_18(x)
#elif defined(COS_PHI_IS_ML2_RAW_WIDE_COS_20)
#define COS_PHI(x) ml2_raw_wide_cos_20(x)
#elif defined(COS_PHI_IS_COS_OPENLIBM)
#define COS_PHI(x) cos_openlibm(x)
#elif defined(COS_PHI_IS_COSF_OPENLIBM)
#define COS_PHI(x) cosf_openlibm(x)
#elif defined(COS_PHI_IS_COS_POVRAY)
#define COS_PHI(x) cos_povray(x)
#elif defined(COS_PHI_IS_COS_VDT)
#define COS_PHI(x) cos_vdt(x)
#elif defined(COS_PHI_IS_COSF_VDT)
#define COS_PHI(x) cosf_vdt(x)
#else
#define COS_PHI(x) cos_crlibm(x)
#endif


#endif // #ifdef USE_CHAR_THETA (else branch)


#endif // #ifndef SIN_COS_SELECTOR_H
