name: CI

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        ocaml-version:
          - 4.11.0
        python-version:
          - 3.8
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade matplotlib numpy sly z3-solver

      - name: Setup ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install ocaml packages
        run: |
          opam install -y num

      - name: Setup other prerequisites
        run: |
          sudo apt install flex bison wget

      - name: Run requirements build script
        run: |
          ./requirements/build.sh

      - name: Run OpTuner
        run: |
          ./bin/optuner benchmarks/logexp.fpcore -e 1e-4