name: CI

on: [push]

jobs:
  test:
    runs-on: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v1
      - name: Build requirements via script
        run: ./requirements/build.sh
