name: CI

on:
  push:
  schedule:
    - cron: '0 10 * * 1'
      
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade sly
        sudo apt install flex bison wget
    - name: Build requirements
      run: |
        ./requirements/build.sh
