name: CI

on: [push]

jobs:
  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: Build requirements via script
    run: ./requirements/build.sh